### ISSUE TITLE
安装后打开页面报错

### ISSUE THREAD

**Issue by ystyleb** [iranee/qnap-aliyunpan-webdav#1]
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by iranee** [comment]
先在威联通的管理页面打开web服务。
位置在：控制台→应用程序→web服务器
如果还有问题，截图发下看有没有系统的错误通知

**Comment by ystyleb** [comment]
> 先在威联通的管理页面打开web服务。
> 位置在：控制台→应用程序→web服务器
> 如果还有问题，截图发下看有没有系统的错误通知

已解决 感谢🙏

**Comment by Unicellular-SU** [comment]
我打开了web服务器还是不行，提示
Not Found
The requested URL was not found on this server.

**Comment by iranee** [comment]
> 我打开了web服务器还是不行，提示
> 
> Not Found
> 
> The requested URL was not found on this server.

删了插件重新下载最新版安装试试

**Comment by lynnial** [comment]
我也碰到同样问题了，打开web server也不行，因为我设置NAS端口80，所以web server默认端口改成了8080，是不是和这个有关系？

**Comment by iranee** [comment]
> 我也碰到同样问题了，打开web server也不行，因为我设置NAS端口80，所以web server默认端口改成了8080，是不是和这个有关系？

跟端口没有关系，这个插件会在web文件夹生成一个aliyunpan文件夹

**Comment by Key033** [comment]
是因为这个插件不支持HTTPS协议，把登陆网址前面改成HTTP就可以了！

**Comment by vicdorke** [comment]
威联通212p超级老机器
一直等待进程检测中，次数：15
进程启动失败！请检查参数是否存在问题
是老机器没办法支持了吗？

**Comment by iranee** [comment]
> 威联通212p超级老机器
> 
> 一直等待进程检测中，次数：15
> 
> 进程启动失败！请检查参数是否存在问题
> 
> 是老机器没办法支持了吗？

这个机器CPU是ARM构架，下载对应ARM的插件试试

**Comment by iranee** [comment]
> 是因为这个插件不支持HTTPS协议，把登陆网址前面改成HTTP就可以了！

这个跟HTTPS协议没有关系，自适应的。估计是因为刚刚开启了web服务，还有缓存，导致网页打不开
如果可以，复现下问题我看看，只要web服务开启不再关闭，不会再出现这个问题

**Comment by vicdorke** [comment]
> > 威联通212p超级老机器
> > 一直等待进程检测中，次数：15
> > 进程启动失败！请检查参数是否存在问题
> > 是老机器没办法支持了吗？
> 
> 这个机器CPU是ARM构架，下载对应ARM的插件试试

我下的arm19，安装上了，一直都是
等待进程检测中，次数：3
我试试其他版本
