### ISSUE TITLE
“目录缓存” 和 “下载缓冲” 如何更改

### ISSUE THREAD

**Issue by chAosForDLB** [iranee/qnap-aliyunpan-webdav#12]
麻烦问下，若阿里云盘数据量较多，挂载卡死， “目录缓存” 和 “下载缓冲” 如何更改呢？

**Comment by iranee** [comment]
> 麻烦问下，若阿里云盘数据量较多，挂载卡死， “目录缓存” 和 “下载缓冲” 如何更改呢？

如果有这两个需求，可以安装低版本1.0.09

**Comment by chAosForDLB** [comment]
> > 麻烦问下，若阿里云盘数据量较多，挂载卡死， “目录缓存” 和 “下载缓冲” 如何更改呢？
> 
> 如果有这两个需求，可以安装低版本1.0.09

谢谢，由于老版本会被qnap误杀，所以再麻烦问下有计划新版本支持更改这两个参数吗？

**Comment by iranee** [comment]
> > > 麻烦问下，若阿里云盘数据量较多，挂载卡死， “目录缓存” 和 “下载缓冲” 如何更改呢？
> > 
> > 
> > 如果有这两个需求，可以安装低版本1.0.09
> 
> 谢谢，由于老版本会被qnap误杀，所以再麻烦问下有计划新版本支持更改这两个参数吗？

这个被QNAP误杀不可预测，因为这个插件用的其他github开源，回来我再试试新版本是否还被误杀
