### ISSUE TITLE
打开提示Service Unavailable

### ISSUE THREAD

**Issue by Aleix-Chen** [iranee/qnap-aliyunpan-webdav#13]
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
请问，出现这个问题，是还需要设置什么吗？

**Comment by iranee** [comment]
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later. 请问，出现这个问题，是还需要设置什么吗？

安装前，去威联通的管理页面打开web服务，位置在：控制台→应用程序→web服务器
然后重启阿里云盘服务

**Comment by Aleix-Chen** [comment]
找到原因了，我web服务是开了，但是下面有一个“不允许web服务器嵌入IFrame中”我是打勾了。取消打勾就好了。
