### ISSUE TITLE
阿里云盘arm64套件最新版 在nas上打开就是连接错误

### ISSUE THREAD

**Issue by AsukaSoryu0** [iranee/qnap-aliyunpan-webdav#14]
![image](https://user-images.githubusercontent.com/86198114/163196082-f0641086-4c7c-478a-997b-3e46cc7a0091.png)
nas是威联通212P3，arm64的cpu

**Comment by AsukaSoryu0** [comment]
1、前天还能用的。
2、今天发现不能用，就卸掉重装了，还是会出现这个问题。

**Comment by MessJuice** [comment]
右键图标，在新建浏览器分页中打开

**Comment by iranee** [comment]
1，管理页面打开web服务，位置在：控制台→应用程序→web服务器
2，在web服务器配置页面，允许加载【iframe网页】

**Comment by AsukaSoryu0** [comment]
> 1，管理页面打开web服务，位置在：控制台→应用程序→web服务器 2，在web服务器配置页面，允许加载【iframe网页】

![image](https://user-images.githubusercontent.com/86198114/163661743-8353c834-d7ff-41b4-9b03-c92ca2051866.png)
可以了，但是挂载之后 一直显示正在挂载。。
