### ISSUE TITLE
1.0.10~1.0.12存在的问题

### ISSUE THREAD

**Issue by 7zheng** [iranee/qnap-aliyunpan-webdav#15]
可能是go语言内核的原因，使用插件挂载，复制多个文件时，会中途断掉。我的机器是TS-212P3。
改用1.0.9，rust内核的版本就没有问题。

**Comment by iranee** [comment]
是的，rust内核很好，就是编译的二进制会被扫描误认为恶意软件而删除。
另外建议用HBS来复制，不要直接在文件管理器里复制

**Comment by 7zheng** [comment]
使用HBS复制可以规避掉中断的问题？算是一个备用方案吧
现在我暂时每次被当作恶意软件就重新装一下~
