### ISSUE TITLE
Token只要不到1周就会显示过期根本无法使用

### ISSUE THREAD

**Issue by huang5307** [iranee/qnap-aliyunpan-webdav#17]
Token只要不到1周就会显示过期，这样根本无法使用嘛！你说1个月失效一次也还好，几天就要重新输入，总不能每天去检查吧！一般NAS不是放在那里就很少去管它了吗？

**Comment by iranee** [comment]
> Token只要不到1周就会显示过期，这样根本无法使用嘛！你说1个月失效一次也还好，几天就要重新输入，总不能每天去检查吧！一般NAS不是放在那里就很少去管它了吗？

如果提示过期，有时候是误报，无需理会，主要问题是NAS系统的规则不允许长时间挂载，而且这个是开源插件，有问题需要去作者那里提问。
