### ISSUE TITLE
安装后一直在重试连接，无法连接上

### ISSUE THREAD

**Issue by wjw054509** [iranee/qnap-aliyunpan-webdav#18]
威联通安装后一直在重试连接，无法连接上

**Comment by iranee** [comment]
- NAS是什么版本？
- 尝试最新版

**Comment by sandy320** [comment]
> * NAS是什么版本？
> * 尝试最新版

我也是，TS-453mini. 固件5.0.0.1932，阿里云盘x86_64 v1.0.13
token过期后就一直连不上

**Comment by WalterDSU** [comment]
> 

你试试停用这个程序, 再启用, 看看会不会发现被发现有病毒, 删了某个文件, 需要重新安装. 应该这个事情. 我也一样. 不能用. 后面重启后发现, 跟之前一样被误删了某个文件, 不能用了. 需要重新安装.  现在用回1.0.12版本. 这个最新版有问题.

**Comment by iranee** [comment]
试试最新的插件 https://github.com/iranee/qnap-alist-webdav
