### ISSUE TITLE
使用HybridMount挂载成本地文件夹时报错

### ISSUE THREAD

**Issue by cyril-cheng** [iranee/qnap-aliyunpan-webdav#2]
可能是不是我网盘资源较多？
当我尝试将阿里云盘的webdav挂载成本地盘的时候总是显示文件目录获取过期，然后挂载失败。
使用HBS3的时候可以正常加载。

**Comment by cyril-cheng** [comment]
我QNAP型号是：TS-453Dmini，J4125的U

**Comment by iranee** [comment]
跟我的NAS一个型号。
这个有可能，你可以去开源作者哪里看看有没有此问题发生。
另外你尝试修改下挂载的目录数，默认是1000
如果想复现问题并告知开发者的话，需要手动SSH运行脚本，获取到具体的错误信息。

**Comment by cyril-cheng** [comment]
好的

**Comment by WalterDSU** [comment]
没有提示token过期了. 但是, 
警告	2022-01-07	18:03:43	System	127.0.0.1	HybridMount	Mount Activity	[HybridMount] Failed to mount. Authentication error. Connection: webdav "Aliyun".
