### ISSUE TITLE
WEB服务器不能使用强制 https

### ISSUE THREAD

**Issue by rabbitlhf** [iranee/qnap-aliyunpan-webdav#20]
开启 WEB服务器使用强制 https 后 ，无法打开 aliyunpan-wedav 设置页面

**Comment by iranee** [comment]
可以使用的，注意你的web HTTPS要有对应的证书。 [运行图](https://cheen.cn/temp/Snipaste_2022-08-28_18-20-07.png)

**Comment by rabbitlhf** [comment]
我放弃使用 qnas 版本了，直接用 docker版了

**Comment by iranee** [comment]
可以在系统-反向代理设置为https
或者试试最新的插件https://github.com/iranee/qnap-alist-webdav
