### ISSUE TITLE
重启后自动挂载的问题。

### ISSUE THREAD

**Issue by befantasy** [iranee/qnap-aliyunpan-webdav#5]
设置后可以使用hybridmount正常挂载挂载。
但是重启后有个问题，应该是因为hybridmount会优先启动，启动的时候阿里云盘还没有启动，所以会造成挂载失败。而且hybridmount比较愚蠢的地方是好像还不会重试。。。filestation里一直刷不出来。

只能在mybridmount里禁用再启用一下。

不知道大家是否也有此问题？该如何解决？

**Comment by iranee** [comment]
这个属于QNAP的锅，暂时无解，除非用脚本实现自动挂载webdav的功能。
我刚刚遇到个问题，hybridmount挂载为云网关模式，重启几次后挂在不上任何webdav，一直到卸载了重新安装才成功。

**Comment by befantasy** [comment]
> 这个属于QNAP的锅，暂时无解，除非用脚本实现自动挂载webdav的功能。 我刚刚遇到个问题，hybridmount挂载程云网关模式，重启几次后挂在不上任何webdav，一直到卸载了重新安装才成功。

会不会是被qnap的安全策略给ban了，把自己给加入到了deny list里了。。。


软件的启动顺序好像是可以调整的，我研究一下。

**Comment by iranee** [comment]
> 

另外能不能研究下，如何调用系统登录的API，来检测系统是否已经登录？
这个web server在外网会被暴漏，容易被窥透。

**Comment by iranee** [comment]
> > 这个属于QNAP的锅，暂时无解，除非用脚本实现自动挂载webdav的功能。 我刚刚遇到个问题，hybridmount挂载程云网关模式，重启几次后挂在不上任何webdav，一直到卸载了重新安装才成功。
> 
> 会不会是被qnap的安全策略给ban了，把自己给加入到了deny list里了。。。
> 
> 软件的启动顺序好像是可以调整的，我研究一下。

我查了查，有说更改/etc/config/qpkg.conf里面的优先顺序，数字越小，优先级越高。
也有做成了插件
https://github.com/OneCDOnly/SortMyQPKGs/blob/main/shared/sortmyqpkgs.sh

**Comment by befantasy** [comment]
谢谢谢谢，看样子是可以实现的。但是估计也没有那么简单，hybridmount和ali的这个插件可能都有dependence，比如阿里这个可能就必须得在httpd之后，我抽空试试看。

对了，今天在别的地方看到的，qnap官方已经在测试支持百度和阿里了，有人拿到了测试版，据说是月底可以放出更新的hybridmount和hybrid backup sync。

**Comment by iranee** [comment]
> 谢谢谢谢，看样子是可以实现的。但是估计也没有那么简单，hybridmount和ali的这个插件可能都有dependence，比如阿里这个可能就必须得在httpd之后，我抽空试试看。
> 
> 对了，今天在别的地方看到的，qnap官方已经在测试支持百度和阿里了，有人拿到了测试版，据说是月底可以放出更新的hybridmount和hybrid backup sync。

百度网盘的测试已经出了，阿里云盘的估计还得推后，拭目以待吧。

**Comment by qingmuhy** [comment]
卧槽，官方要支持了。牛逼……
