### ISSUE TITLE
ARM64 版本的，经过一次token失效之后，再换token就无法连接了。

### ISSUE THREAD

**Issue by goofysun** [iranee/qnap-aliyunpan-webdav#6]
现象如标题：经过一次token失效之后，再换token就无法连接了。

尝试操作：
1、停用再启用  无效
2、切换 token 无效
3、删除 应用 然后 重装 ，有效……

就是每次 token 过期，都要删除 应用重装才可以

**Comment by iranee** [comment]
测试期间发现一次问题，启动文件被删除了，不知道是哪里出的问题，导致被删除，只能重装。后续再观察下或者看看能不能复现问题

**Comment by iMVP007** [comment]
X86出现同样的问题，重装有效。
重启系统也不行。

**Comment by iranee** [comment]
每一次点击保存，都会结束aliyunpan的进程，需要等待20-30秒进程重启。
也就是说点过保存后，关闭配置页面，等待几秒再打开配置页面，看看是否运行成功。
我这里测试暂时没有出现过问题。或者联系我的QQ，我帮你们定位下问题

**Comment by lovelyjuice** [comment]
同样的问题，怀疑是威联通自带的Malware Remover误删了文件，可以去日志里看看Malware Remover有没有报警

**Comment by kyalpha313** [comment]
> 同样的问题，怀疑是威联通自带的Malware Remover误删了文件，可以去日志里看看Malware Remover有没有报警

日志里有个Removed the detected malware: MR2104，没有更详细的诊断信息了。这个Malware Remover也太敷衍了……

**Comment by kyalpha313** [comment]
> X86出现同样的问题，重装有效。 重启系统也不行。

653D，完全一致

**Comment by lovelyjuice** [comment]
日志显示如下警告 "警告 2021-12-07 05:21:48 admin 127.0.0.1 Malware Remover Malware Removal [Malware Remover] 已删除检测到的恶意软件: MR2104 。" 怀疑是误报，如何恢复被删除的原文件？以及日志中为何缺少原文件的相关信息？如文件名、路径、大小、创建日期、修改日期。

 Deng Zhang
 2021-12-10 20:38:51

您好，

请先把固件手动升级到最新的 ：https://download.qnap.com.cn/Storage/TS-X53D/TS-X53D_20211201-5.0.0.1870.zip

控制台-系统-固件更新。再观察是否还是会报类似资讯

如果还是报此类似资讯，请参考附件截图 下载一份NAS 系统日志。谢谢！


感谢您使用QNAP产品，祝您生活愉快！ 


上面是我提交给威联通的工单，以及威联通回复的解决办法，仅供参考，如无卵用，纯属意外

**Comment by iranee** [comment]
不是自带的Malware删除的，自带杀毒删除的文件可以在 控制台-> 应用程序->病毒防护 ->隔离区 找到被删除/隔离的文件

我怀疑是服务脚本的问题，我再重新打包一次，你们升级下试试

**Comment by kyalpha313** [comment]
错误	2021-12-25	10:27:15	Kevin	192.168.2.100	App Center	App Installation	[App Center] Failed to install aliyunpan_1.0.09_x86_64.qpkg. Try again later.
新版装不上，在哪能看到更详细的日志以便反馈呢？我的是653D，装1.08的x86包正常

**Comment by iranee** [comment]
> 错误 2021-12-25 10:27:15 Kevin 192.168.2.100 App Center App Installation [App Center] Failed to install aliyunpan_1.0.09_x86_64.qpkg. Try again later. 新版装不上，在哪能看到更详细的日志以便反馈呢？我的是653D，装1.08的x86包正常

我这里测试都正常，看看是哪里出现的问题，我再一次重新打包，试试

**Comment by kyalpha313** [comment]
第一次安装成功但是卡重试，卸载了以后重装外加换了个端口好了，观察几天再反馈。
谢谢大佬！

**Comment by goofysun** [comment]
1.0.09 问题依旧
![image](https://user-images.githubusercontent.com/1747913/147431320-8c640475-89e3-44ea-b2c4-aaf0b62add19.png)

**Comment by iranee** [comment]
> 1.0.09 问题依旧
> 
> ![image](https://user-images.githubusercontent.com/1747913/147431320-8c640475-89e3-44ea-b2c4-aaf0b62add19.png)
> 
> 

还真的检测出来了，看来是某个变量出现问题，如果可以的话，我帮你排查下，加我QQ 195408188

**Comment by bilijinshi** [comment]
同样问题

**Comment by iranee** [comment]
已经提交给开源作者，看看后续有没有办法修复

**Comment by iranee** [comment]
更换内核，试试最新版

**Comment by GOUKI9999** [comment]
x86_64版本，最新的1.0.13，仍然有这个问题，确认了token正确，其他设备可挂载，但威联通的ppkg版本莫名失败之后无论如何无法启动

**Comment by iranee** [comment]
> x86_64版本，最新的1.0.13，仍然有这个问题，确认了token正确，其他设备可挂载，但威联通的ppkg版本莫名失败之后无论如何无法启动

新版本采用了自动更新token方式，估计上个token失效后，没有自动更新，导致新的token录入也不可用，我看看改个版本
