### ISSUE TITLE
[求助] TS-231P 显示进程启动失败

### ISSUE THREAD

**Issue by voodka** [iranee/qnap-aliyunpan-webdav#7]
TS-231P装了插件arm-x41的qpkg安装成功，但是填写token之后一直显示进程启动失败，请问大佬是怎么回事呀？截图如下[https://wx2.sinaimg.cn/mw690/a46113a7ly1gxgr6ctd69j20g40f20tc.jpg]

**Comment by iranee** [comment]
更新最新版本试试
