### ISSUE TITLE
QNAP Malware Remover报恶意软件

### ISSUE THREAD

**Issue by janus2xss** [iranee/qnap-aliyunpan-webdav#8]
警告	2021-12-30	03:00:53	admin	127.0.0.1	Malware Remover	Malware Removal	[Malware Remover] Removed the detected malware: MR2104
.
如上，系统报恶意软件并自动删除，可以优化处理一下吗？

**Comment by iranee** [comment]
我这里测试确实有这个问题，已经提交给开源作者

**Comment by iranee** [comment]
更换内核，试试最新版

**Comment by janus2xss** [comment]
> 更换内核，试试最新版

已解决，谢谢。
